AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  WPServiceName:
    Type: String
    Description: ECR Repository Name


Resources:
  WPServiceRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref WPServiceName

Outputs:
  WPServiceRepository:
    Value: !Ref 'WPServiceRepository'
    Export:
      Name: !Sub '${AWS::StackName}-WPServiceRepository'
  WPServiceRepositoryUrl:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${WPServiceRepository}"
    Export:
      Name: !Sub '${AWS::StackName}-WPServiceRepositoryUrl'
      